links:
  imports: UnityProject/Assets/Plugins
  exports: Sources
dependencies:
  - repo: "git@github.com:silphid/silphid.log4net.git"
    branch: master
  - repo: "git@github.com:silphid/silphid.unirx.git"
    branch: master
  - repo: "git@github.com:silphid/silphid.yamldotnet.git"
    branch: master
